server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        # 认证中心路由
        - id: auth_route
          uri: lb://talent-auth
          predicates:
            - Path=/api/auth/**
        # 岗位与投递路由
        - id: job_route
          uri: lb://talent-job
          predicates:
            - Path=/api/job/**, /api/delivery/**
        # 简历底座路由
        - id: resume_route
          uri: lb://talent-resume
          predicates:
            - Path=/api/resume/**
        # AI 智能体对外路由
        - id: ai_route
          uri: lb://talent-ai-agent
          predicates:
            - Path=/api/ai/**
        # AI 智能体服务间内部路由
        - id: ai_internal_route
          uri: lb://talent-ai-agent
          predicates:
            - Path=/internal/ai/**
        # 面试管理路由
        - id: interview_route
          uri: lb://talent-interview
          predicates:
            - Path=/api/interview/**
        # 面试服务间内部路由
        - id: interview_internal_route
          uri: lb://talent-interview
          predicates:
            - Path=/internal/interview/**
        # 让网关认识 offer
        -  id: talent-offer-route
           uri: lb://talent-job  # 路由到你的 talent-job 服务
           predicates:
               - Path=/api/offer/**
           filters:
               - StripPrefix=1 # 转发时脱掉 /api，后端 Controller 只需要填 /offer

        # B2 的人才库
        -  id: talent-pool-route
           uri: lb://talent-talent-pool
           predicates:
                - Path=/api/talent-pool/**
           filters:
                - StripPrefix=1
        # 岗位与投递路由
        -  id: job_route
           uri: lb://talent-job
           predicates:
              - Path=/api/job/**, /api/delivery/**, /api/jobApplication/**  # 补上这个路径
           filters:
              - StripPrefix=1  # 确保有这一行，用来剥离 /api
