server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 重点：换成 talent_job_db
    url: jdbc:mysql://127.0.0.1:3306/talent_job_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: dyq!