server:
  port: 8080 # 网关对外端口

spring:
  application:
    name: talent-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 地址
    gateway:
      routes:
        # 配置认证授权服务的路由
        - id: talent-auth-route
          uri: lb://talent-auth        # lb代表负载均衡，将请求转发给 Nacos 中名为 talent-auth 的服务
          predicates:
            - Path=/api/auth/** # 匹配所有以 /api/auth/ 开头的请求路径
          filters:
            - StripPrefix=2            # 【关键】截掉路径的前2段（去掉 /api/auth），这样发给子服务的真实路径刚好就是 /login